import { Product } from './product';

export const PRODUCTS: Product[] = [
  // 🔥 Anti-inflammatoires
  {
    id: 1,
    name: 'Aspirin',
    description:
      'Utilisé pour traiter les douleurs, la fièvre et les inflammations.',
    price: 10,
    image: 'assets/img/products/aspirine-100-30-comprimes.webp',
    categoryId: 1,
    quantity: 10,
    pharmacyId: 1,
  },
  {
    id: 2,
    name: 'Paracetamol',
    description: 'Médicament contre la douleur et la fièvre.',
    price: 20,
    image: 'assets/img/products/paracetamol.webp',
    categoryId: 1,
    quantity: 20,
    pharmacyId: 2,
  },
  {
    id: 3,
    name: 'Ibuprofène',
    description: 'Anti-inflammatoire et analgésique.',
    price: 30,
    image: 'assets/img/products/ibuprofen-teva-gel-50-g.webp',
    categoryId: 1,
    quantity: 30,
    pharmacyId: 1,
  },
  {
    id: 4,
    name: 'Diclofénac',
    description: 'Soulage les douleurs musculaires et articulaires.',
    price: 25,
    image: 'assets/img/products/diclofenac.jpeg',
    categoryId: 1,
    quantity: 15,
    pharmacyId: 3,
  },

  // 💊 Antibiotiques
  {
    id: 5,
    name: 'Amoxicilline',
    description:
      'Antibiotique utilisé contre diverses infections bactériennes.',
    price: 15,
    image: 'assets/img/products/Amoxicilline.jpeg',
    categoryId: 2,
    quantity: 50,
    pharmacyId: 1,
  },
  {
    id: 6,
    name: 'Ciprofloxacine',
    description: 'Antibiotique puissant contre les infections urinaires.',
    price: 22,
    image: 'assets/img/products/ciprofloxacine.jpeg',
    categoryId: 2,
    quantity: 40,
    pharmacyId: 2,
  },
  {
    id: 7,
    name: 'Azithromycine',
    description: 'Utilisé contre les infections ORL et pulmonaires.',
    price: 18,
    image: 'assets/img/products/azithromycine.jpeg',
    categoryId: 2,
    quantity: 30,
    pharmacyId: 3,
  },

  // ⚡ Analgésiques
  {
    id: 8,
    name: 'Codéine',
    description: 'Analgésique opioïde contre les douleurs modérées.',
    price: 35,
    image: 'assets/img/products/codeine.jpeg',
    categoryId: 3,
    quantity: 25,
    pharmacyId: 1,
  },
  {
    id: 9,
    name: 'Tramadol',
    description: 'Utilisé pour les douleurs chroniques sévères.',
    price: 40,
    image: 'assets/img/products/tramadol.jpeg',
    categoryId: 3,
    quantity: 20,
    pharmacyId: 2,
  },

  // 🌞 Vitamines
  {
    id: 11,
    name: 'Vitamine C',
    description: 'Renforce le système immunitaire.',
    price: 10,
    image: 'assets/img/products/vitamineC.jpeg',
    categoryId: 4,
    quantity: 60,
    pharmacyId: 1,
  },
  {
    id: 12,
    name: 'Vitamine D',
    description: 'Essentielle pour la santé des os et des muscles.',
    price: 15,
    image: 'assets/img/products/vitamineD.jpeg',
    categoryId: 4,
    quantity: 50,
    pharmacyId: 2,
  },

  // 💪 Suppléments
  {
    id: 14,
    name: 'Magnésium',
    description: 'Réduit la fatigue et améliore la concentration.',
    price: 12,
    image: 'assets/img/products/magnesium.jpeg',
    categoryId: 5,
    quantity: 40,
    pharmacyId: 1,
  },
  {
    id: 15,
    name: 'Oméga-3',
    description: 'Bénéfique pour la santé du cœur et du cerveau.',
    price: 25,
    image: 'assets/img/products/omega3.jpeg',
    categoryId: 5,
    quantity: 35,
    pharmacyId: 2,
  },
];
